# Order Data Cleaning and Analysis

### Reading the file

In [1]:
import pandas as pd

file_path = "pandas_dataset.csv"
df = pd.read_csv("pandas_dataset.csv")

print("Shape before cleaning:", df.shape)
df.head()

Shape before cleaning: (27, 12)

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
2,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
3,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
4,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0

### Rename column+Clean the dataset+Drop rows

In [2]:
# Remove rows that contain no data and reset the index.
df = df.dropna(how="all").reset_index(drop=True)

# Clean the column names.
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_", regex=False)
)

print("Cleaned columns:")
print(df.columns.tolist())
df.head(5)

Cleaned columns:
['order_id', 'customer_name', 'category', 'product', 'city', 'quantity', 'unit_price', 'order_date', 'status', 'sales', 'profit', 'discount']

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0

### Check missing values

In [3]:
missing_values = df.isna().sum()
display(missing_values.to_frame("missing_values"))

               missing_values
order_id                    0
customer_name               1
category                    0
product                     0
city                        1
quantity                    1
unit_price                  1
order_date                  0
status                      1
sales                       3
profit                      3
discount                    3

### Count and handle missing values

In [ ]:
df["customer_name"] = df["customer_name"].fillna("Unknown")

if "profit" in df.columns:
    df["profit"] = df["profit"].fillna(df["profit"].mean())

if "discount" in df.columns:
    df["discount"] = df["discount"].fillna(df["discount"].median())

print("Missing values after handling:")
display(df.isna().sum().to_frame("missing_values"))

Missing values after handling:

               missing_values
order_id                    0
customer_name               0
category                    0
product                     0
city                        1
quantity                    1
unit_price                  1
order_date                  0
status                      1
sales                       3
profit                      0
discount                    0

### Remove duplicate orders

In [5]:
duplicate_mask = df["order_id"].duplicated(keep=False)

print("Duplicate orders:")
display(df.loc[duplicate_mask].sort_values("order_id"))

removed_duplicates = df["order_id"].duplicated().sum()
df = df.drop_duplicates(subset="order_id", keep="first").reset_index(drop=True)

print("Duplicates removed:", removed_duplicates)

Duplicate orders:

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
20,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000.0,10000.0,5000.0
21,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000.0,10000.0,5000.0
12,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,2/18/2026,Completed,56000.0,11200.0,5600.0
22,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,2/18/2026,Completed,56000.0,11200.0,5600.0

Duplicates removed: 3

### Filter orders

In [6]:
print("Orders with unit_price greater than 20,000:")
display(df[df["unit_price"] > 20000].reset_index(drop=True))

Orders with unit_price greater than 20,000:

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0
2,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000.0,10000.0,5000.0
3,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,2/18/2026,Completed,56000.0,11200.0,5600.0
4,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,3/5/2026,Completed,22000.0,4400.0,1100.0
5,1024.0,Nisha,Electronics,Mouse,Kathmandu,2.0,85000.0,1/5/2026,Completed,NaN,600.0,150.0

In [7]:
print("Completed orders with unit_price greater than 10,000:")
display(
    df.loc[
        (df["unit_price"] > 10000) & (df["status"] == "Completed"),
        ["customer_name", "category", "status"]
    ].reset_index(drop=True)
)

Completed orders with unit_price greater than 10,000:

  customer_name     category     status
0         Aarav  Electronics  Completed
1          Sita    Furniture  Completed
2         Nabin    Furniture  Completed
3        Roshan  Electronics  Completed
4         Manoj    Furniture  Completed
5          Rita  Electronics  Completed
6         Nisha  Electronics  Completed
7        Bikash    Furniture  Completed

### Create new columns

In [8]:
df["total_amount"] = df["quantity"] * df["unit_price"]

df["customer_type"] = df["quantity"].apply(
    lambda x: "Bulk Buyer" if x >= 3 else "Regular Buyer"
)

display(
    df[["order_id", "customer_name", "quantity",
        "unit_price", "total_amount", "customer_type"]]
    .head(10)
)

   order_id customer_name  quantity  unit_price  total_amount  customer_type
0    1001.0         Aarav       2.0     85000.0      170000.0  Regular Buyer
1    1002.0          Sita       1.0     18000.0       18000.0  Regular Buyer
2    1003.0         Rohan       3.0      4500.0       13500.0     Bulk Buyer
3    1004.0        Anisha       2.0      6500.0       13000.0  Regular Buyer
4    1005.0         Bibek       1.0     55000.0       55000.0  Regular Buyer
5    1006.0        Pragya       4.0      2200.0        8800.0     Bulk Buyer
6    1007.0         Nabin       2.0     25000.0       50000.0  Regular Buyer
7    1008.0         Samir       3.0      7500.0       22500.0     Bulk Buyer
8    1009.0          Puja       1.0         NaN           NaN  Regular Buyer
9    1010.0         Kiran       2.0      3500.0        7000.0  Regular Buyer

### Final cleaned dataset with sales row removed

In [7]:
print("Shape before cleaning:", (25, 9))
df = df.dropna(subset=["sales"])
print("Shape after cleaning:", df.shape)

print("First 10 rows:")
display(df.head(50))

Shape before cleaning: (25, 9)
Shape after cleaning: (23, 12)
First 10 rows:

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.000000,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.000000,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.000000,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.000000,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.000000,5500.0
5,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,1/22/2026,Completed,8800.0,1760.000000,440.0
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000.0,10000.000000,5000.0
7,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,2/2/2026,Pending,22500.0,4500.000000,1125.0
9,1010.0,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,2/9/2026,Completed,7000.0,1400.000000,350.0
10,1011.0,Mina,Clothing,T-Shirt,Kathmandu,5.0,1800.0,2/12/2026,Completed,9000.0,1800.000000,450.0
11,1012.0,Suman,Furniture,Bookshelf,Pokhara,1.0,15000.0,2/15/2026,NaN,15000.0,3000.000000,750.0
12,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,2/18/2026,Completed,56000.0,11200.000000,5600.0
13,1014.0,Kabita,Books,SQL Book,Kathmandu,3.0,2800.0,2/20/2026,Completed,8400.0,1680.000000,420.0
14,1015.0,Unknown,Clothing,Jeans,Bhaktapur,2.0,4200.0,2/23/2026,Cancelled,8400.0,1680.000000,420.0
15,1016.0,Alisha,Electronics,Keyboard,Pokhara,4.0,3500.0,3/1/2026,Completed,14000.0,2800.000000,700.0
16,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,3/5/2026,Completed,22000.0,4400.000000,1100.0
17,1018.0,Sneha,Clothing,Sweater,Lalitpur,2.0,5000.0,3/8/2026,Pending,10000.0,2000.000000,500.0
19,1020.0,Rita,Electronics,Smart Watch,Kathmandu,2.0,12000.0,3/15/2026,Completed,24000.0,4800.000000,1200.0
20,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.000000,17000.0
21,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000.0,10000.000000,5000.0
22,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,2/18/2026,Completed,56000.0,11200.000000,5600.0
24,1025.0,Bikash,Furniture,Lamp,Lalitpur,1.0,18000.0,1/8/2026,Completed,9000.0,7031.304348,450.0
25,1026.0,Sarita,Electronics,Shirt,Bhaktapur,3.0,4500.0,1/12/2026,Pending,5000.0,1000.000000,750.0